/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authentication extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> {

	private static final long serialVersionUID = -2033426117;

	/**
	 * The singleton instance of <code>public.authentication</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Authentication AUTHENTICATION = new be.wolkmaan.klimtoren.heart.model.tables.Authentication();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord.class;
	}

	/**
	 * The column <code>public.authentication.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.authentication.username</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.authentication.password</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.authentication.lastlogin_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.time.LocalDateTime> LASTLOGIN_DATETIME = createField("lastlogin_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.authentication.lastloginattemptfailure_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.time.LocalDateTime> LASTLOGINATTEMPTFAILURE_DATETIME = createField("lastloginattemptfailure_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.authentication.loginattemptfailurecount</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.Integer> LOGINATTEMPTFAILURECOUNT = createField("loginattemptfailurecount", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.authentication.isgranted</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.Boolean> ISGRANTED = createField("isgranted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.authentication.islocked</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.Boolean> ISLOCKED = createField("islocked", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>public.authentication.enableautounlock</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, java.lang.Boolean> ENABLEAUTOUNLOCK = createField("enableautounlock", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * Create a <code>public.authentication</code> table reference
	 */
	public Authentication() {
		this("authentication", null);
	}

	/**
	 * Create an aliased <code>public.authentication</code> table reference
	 */
	public Authentication(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION);
	}

	private Authentication(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Authentication(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.AUTHENTICATION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.AUTHENTICATION_PKEY, be.wolkmaan.klimtoren.heart.model.Keys.AUTHENTICATION_USERNAME_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.AUTHENTICATION__AUTHENTICATION_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Authentication as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Authentication(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Authentication rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Authentication(name, null);
	}
}
