/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Countries extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> {

	private static final long serialVersionUID = -2080558681;

	/**
	 * The singleton instance of <code>public.countries</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Countries COUNTRIES = new be.wolkmaan.klimtoren.heart.model.tables.Countries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord.class;
	}

	/**
	 * The column <code>public.countries.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.countries.code</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.countries.name</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.countries</code> table reference
	 */
	public Countries() {
		this("countries", null);
	}

	/**
	 * Create an aliased <code>public.countries</code> table reference
	 */
	public Countries(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES);
	}

	private Countries(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Countries(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_COUNTRIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.COUNTRIES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.COUNTRIES_PKEY, be.wolkmaan.klimtoren.heart.model.Keys.COUNTRIES_CODE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Countries as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Countries(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Countries rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Countries(name, null);
	}
}
