/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emails extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> {

	private static final long serialVersionUID = -168462725;

	/**
	 * The singleton instance of <code>public.emails</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Emails EMAILS = new be.wolkmaan.klimtoren.heart.model.tables.Emails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord.class;
	}

	/**
	 * The column <code>public.emails.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.emails.url</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, java.lang.String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(320), this, "");

	/**
	 * The column <code>public.emails.customtype</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, java.lang.String> CUSTOMTYPE = createField("customtype", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.emails</code> table reference
	 */
	public Emails() {
		this("emails", null);
	}

	/**
	 * Create an aliased <code>public.emails</code> table reference
	 */
	public Emails(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS);
	}

	private Emails(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Emails(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.EMAILS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.EMAILS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.EMAILS__EMAILS_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Emails as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Emails(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Emails rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Emails(name, null);
	}
}
