/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fullnames extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> {

	private static final long serialVersionUID = 1054144969;

	/**
	 * The singleton instance of <code>public.fullnames</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Fullnames FULLNAMES = new be.wolkmaan.klimtoren.heart.model.tables.Fullnames();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord.class;
	}

	/**
	 * The column <code>public.fullnames.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.fullnames.forparty</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.Integer> FORPARTY = createField("forparty", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.fullnames.startdate</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.sql.Date> STARTDATE = createField("startdate", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>public.fullnames.enddate</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.sql.Date> ENDDATE = createField("enddate", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.fullnames.givenname</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.String> GIVENNAME = createField("givenname", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>public.fullnames.middlename</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.String> MIDDLENAME = createField("middlename", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>public.fullnames.surname</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>public.fullnames.title</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.fullnames.nickname</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.fullnames.pronunciation</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.String> PRONUNCIATION = createField("pronunciation", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.fullnames.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * Create a <code>public.fullnames</code> table reference
	 */
	public Fullnames() {
		this("fullnames", null);
	}

	/**
	 * Create an aliased <code>public.fullnames</code> table reference
	 */
	public Fullnames(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES);
	}

	private Fullnames(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Fullnames(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_FULLNAMES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.FULLNAMES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.FULLNAMES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.FULLNAMES__FULLNAMES_FORPARTY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Fullnames as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Fullnames(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Fullnames rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Fullnames(name, null);
	}
}
