/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Locations extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> {

	private static final long serialVersionUID = -1691953238;

	/**
	 * The singleton instance of <code>public.locations</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Locations LOCATIONS = new be.wolkmaan.klimtoren.heart.model.tables.Locations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord.class;
	}

	/**
	 * The column <code>public.locations.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.locations.creation_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, java.time.LocalDateTime> CREATION_DATETIME = createField("creation_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.locations.modified_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, java.time.LocalDateTime> MODIFIED_DATETIME = createField("modified_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.locations.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * Create a <code>public.locations</code> table reference
	 */
	public Locations() {
		this("locations", null);
	}

	/**
	 * Create an aliased <code>public.locations</code> table reference
	 */
	public Locations(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS);
	}

	private Locations(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Locations(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_LOCATIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.LOCATIONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.LOCATIONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Locations as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Locations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Locations rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Locations(name, null);
	}
}
