/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mailboxes extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> {

	private static final long serialVersionUID = 1408931678;

	/**
	 * The singleton instance of <code>public.mailboxes</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Mailboxes MAILBOXES = new be.wolkmaan.klimtoren.heart.model.tables.Mailboxes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord.class;
	}

	/**
	 * The column <code>public.mailboxes.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.mailboxes.street</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.String> STREET = createField("street", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.mailboxes.zip</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>public.mailboxes.city</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.mailboxes.stateorprovince</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.String> STATEORPROVINCE = createField("stateorprovince", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.mailboxes.country</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.Integer> COUNTRY = createField("country", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.mailboxes.customtype</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, java.lang.String> CUSTOMTYPE = createField("customtype", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.mailboxes</code> table reference
	 */
	public Mailboxes() {
		this("mailboxes", null);
	}

	/**
	 * Create an aliased <code>public.mailboxes</code> table reference
	 */
	public Mailboxes(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES);
	}

	private Mailboxes(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Mailboxes(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.MAILBOXES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.MAILBOXES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.MAILBOXES__MAILBOXES_ID_FKEY, be.wolkmaan.klimtoren.heart.model.Keys.MAILBOXES__MAILBOXES_COUNTRY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Mailboxes as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Mailboxes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Mailboxes rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Mailboxes(name, null);
	}
}
