/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> {

	private static final long serialVersionUID = 1614384005;

	/**
	 * The singleton instance of <code>public.organizations</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Organizations ORGANIZATIONS = new be.wolkmaan.klimtoren.heart.model.tables.Organizations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord.class;
	}

	/**
	 * The column <code>public.organizations.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.organizations</code> table reference
	 */
	public Organizations() {
		this("organizations", null);
	}

	/**
	 * Create an aliased <code>public.organizations</code> table reference
	 */
	public Organizations(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Organizations.ORGANIZATIONS);
	}

	private Organizations(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Organizations(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.ORGANIZATIONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.ORGANIZATIONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.ORGANIZATIONS__ORGANIZATIONS_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Organizations as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Organizations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Organizations rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Organizations(name, null);
	}
}
