/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class P2pRelations extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> {

	private static final long serialVersionUID = 1185097096;

	/**
	 * The singleton instance of <code>public.p2p_relations</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.P2pRelations P2P_RELATIONS = new be.wolkmaan.klimtoren.heart.model.tables.P2pRelations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord.class;
	}

	/**
	 * The column <code>public.p2p_relations.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.p2p_relations.start_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.time.LocalDateTime> START_DATETIME = createField("start_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.p2p_relations.end_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.time.LocalDateTime> END_DATETIME = createField("end_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.p2p_relations.context</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.lang.Integer> CONTEXT = createField("context", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.p2p_relations.reference</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.lang.Integer> REFERENCE = createField("reference", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.p2p_relations.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * Create a <code>public.p2p_relations</code> table reference
	 */
	public P2pRelations() {
		this("p2p_relations", null);
	}

	/**
	 * Create an aliased <code>public.p2p_relations</code> table reference
	 */
	public P2pRelations(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS);
	}

	private P2pRelations(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private P2pRelations(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_P2P_RELATIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.P2P_RELATIONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.P2P_RELATIONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.P2P_RELATIONS__P2P_RELATIONS_CONTEXT_FKEY, be.wolkmaan.klimtoren.heart.model.Keys.P2P_RELATIONS__P2P_RELATIONS_REFERENCE_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.P2pRelations as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.P2pRelations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.P2pRelations rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.P2pRelations(name, null);
	}
}
