/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parties extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> {

	private static final long serialVersionUID = -1254151114;

	/**
	 * The singleton instance of <code>public.parties</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Parties PARTIES = new be.wolkmaan.klimtoren.heart.model.tables.Parties();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord.class;
	}

	/**
	 * The column <code>public.parties.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.parties.display_name</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, java.lang.String> DISPLAY_NAME = createField("display_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.parties.descriptive_information</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, java.lang.String> DESCRIPTIVE_INFORMATION = createField("descriptive_information", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.parties.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * Create a <code>public.parties</code> table reference
	 */
	public Parties() {
		this("parties", null);
	}

	/**
	 * Create an aliased <code>public.parties</code> table reference
	 */
	public Parties(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES);
	}

	private Parties(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Parties(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_PARTIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Parties as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Parties(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Parties rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Parties(name, null);
	}
}
