/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyAttributes extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> {

	private static final long serialVersionUID = -1174044632;

	/**
	 * The singleton instance of <code>public.party_attributes</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes PARTY_ATTRIBUTES = new be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord.class;
	}

	/**
	 * The column <code>public.party_attributes.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.party_attributes.start_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.time.LocalDateTime> START_DATETIME = createField("start_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.party_attributes.end_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.time.LocalDateTime> END_DATETIME = createField("end_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.party_attributes.name</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.party_attributes.value</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.party_attributes.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * The column <code>public.party_attributes.forparty</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.Long> FORPARTY = createField("forparty", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>public.party_attributes</code> table reference
	 */
	public PartyAttributes() {
		this("party_attributes", null);
	}

	/**
	 * Create an aliased <code>public.party_attributes</code> table reference
	 */
	public PartyAttributes(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES);
	}

	private PartyAttributes(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> aliased) {
		this(alias, aliased, null);
	}

	private PartyAttributes(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_PARTY_ATTRIBUTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.PARTY_ATTRIBUTES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.PARTY_ATTRIBUTES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.PARTY_ATTRIBUTES__PARTY_ATTRIBUTES_FORPARTY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes(name, null);
	}
}
