/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Persons extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> {

	private static final long serialVersionUID = 125827595;

	/**
	 * The singleton instance of <code>public.persons</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Persons PERSONS = new be.wolkmaan.klimtoren.heart.model.tables.Persons();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord.class;
	}

	/**
	 * The column <code>public.persons.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.persons.gender</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord, be.wolkmaan.klimtoren.heart.enums.Gender> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(6), this, "", new be.wolkmaan.klimtoren.heart.enums.GenderConverter());

	/**
	 * Create a <code>public.persons</code> table reference
	 */
	public Persons() {
		this("persons", null);
	}

	/**
	 * Create an aliased <code>public.persons</code> table reference
	 */
	public Persons(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS);
	}

	private Persons(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Persons(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.PERSONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.PERSONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.PERSONS__PERSONS_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Persons as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Persons(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Persons rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Persons(name, null);
	}
}
