/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceAttributes extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> {

	private static final long serialVersionUID = -796576334;

	/**
	 * The singleton instance of <code>public.resource_attributes</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes RESOURCE_ATTRIBUTES = new be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord.class;
	}

	/**
	 * The column <code>public.resource_attributes.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.resource_attributes.start_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.time.LocalDateTime> START_DATETIME = createField("start_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.resource_attributes.end_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.time.LocalDateTime> END_DATETIME = createField("end_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.resource_attributes.name</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.resource_attributes.value</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.resource_attributes.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * The column <code>public.resource_attributes.forresource</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.Integer> FORRESOURCE = createField("forresource", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.resource_attributes.forparty</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.Integer> FORPARTY = createField("forparty", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.resource_attributes</code> table reference
	 */
	public ResourceAttributes() {
		this("resource_attributes", null);
	}

	/**
	 * Create an aliased <code>public.resource_attributes</code> table reference
	 */
	public ResourceAttributes(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES);
	}

	private ResourceAttributes(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ResourceAttributes(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_RESOURCE_ATTRIBUTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.RESOURCE_ATTRIBUTES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCE_ATTRIBUTES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORRESOURCE_FKEY, be.wolkmaan.klimtoren.heart.model.Keys.RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORPARTY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes(name, null);
	}
}
