/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resources extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> {

	private static final long serialVersionUID = -1603642256;

	/**
	 * The singleton instance of <code>public.resources</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Resources RESOURCES = new be.wolkmaan.klimtoren.heart.model.tables.Resources();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord.class;
	}

	/**
	 * The column <code>public.resources.id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.resources.start_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.time.LocalDateTime> START_DATETIME = createField("start_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.resources.end_datetime</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.time.LocalDateTime> END_DATETIME = createField("end_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new be.wolkmaan.klimtoren.heart.enums.LocalDateTimeConverter());

	/**
	 * The column <code>public.resources.owner</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.Integer> OWNER = createField("owner", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.resources.kind</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, be.wolkmaan.klimtoren.heart.enums.Kind> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "", new be.wolkmaan.klimtoren.heart.enums.KindConverter());

	/**
	 * The column <code>public.resources.parent</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.Integer> PARENT = createField("parent", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.resources.displayName</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.String> DISPLAYNAME = createField("displayName", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>public.resources</code> table reference
	 */
	public Resources() {
		this("resources", null);
	}

	/**
	 * Create an aliased <code>public.resources</code> table reference
	 */
	public Resources(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES);
	}

	private Resources(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Resources(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.Integer> getIdentity() {
		return be.wolkmaan.klimtoren.heart.model.Keys.IDENTITY_RESOURCES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, ?>>asList(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES__RESOURCES_OWNER_FKEY, be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES__RESOURCES_PARENT_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Resources as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Resources(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Resources rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Resources(name, null);
	}
}
