/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Telephones extends org.jooq.impl.TableImpl<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> {

	private static final long serialVersionUID = 656905054;

	/**
	 * The singleton instance of <code>public.telephones</code>
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Telephones TELEPHONES = new be.wolkmaan.klimtoren.heart.model.tables.Telephones();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> getRecordType() {
		return be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord.class;
	}

	/**
	 * The column <code>public.telephones.location_id</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord, java.lang.Integer> LOCATION_ID = createField("location_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.telephones.number</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord, java.lang.String> NUMBER = createField("number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.telephones.customtype</code>.
	 */
	public final org.jooq.TableField<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord, java.lang.String> CUSTOMTYPE = createField("customtype", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.telephones</code> table reference
	 */
	public Telephones() {
		this("telephones", null);
	}

	/**
	 * Create an aliased <code>public.telephones</code> table reference
	 */
	public Telephones(java.lang.String alias) {
		this(alias, be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES);
	}

	private Telephones(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Telephones(java.lang.String alias, org.jooq.Table<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> getPrimaryKey() {
		return be.wolkmaan.klimtoren.heart.model.Keys.TELEPHONES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord>>asList(be.wolkmaan.klimtoren.heart.model.Keys.TELEPHONES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.model.tables.Telephones as(java.lang.String alias) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Telephones(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.wolkmaan.klimtoren.heart.model.tables.Telephones rename(java.lang.String name) {
		return new be.wolkmaan.klimtoren.heart.model.tables.Telephones(name, null);
	}
}
