/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailsRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 2063007261;

	/**
	 * Setter for <code>public.emails.id</code>.
	 */
	public EmailsRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.emails.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.emails.url</code>.
	 */
	public EmailsRecord setUrl(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.emails.url</code>.
	 */
	@javax.validation.constraints.Size(max = 320)
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.emails.customtype</code>.
	 */
	public EmailsRecord setCustomtype(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.emails.customtype</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getCustomtype() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS.CUSTOMTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCustomtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailsRecord value2(java.lang.String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailsRecord value3(java.lang.String value) {
		setCustomtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmailsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmailsRecord
	 */
	public EmailsRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS);
	}

	/**
	 * Create a detached, initialised EmailsRecord
	 */
	public EmailsRecord(java.lang.Integer id, java.lang.String url, java.lang.String customtype) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS);

		setValue(0, id);
		setValue(1, url);
		setValue(2, customtype);
	}
}
