/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventlogRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord> implements org.jooq.Record7<java.lang.Long, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.String, java.time.LocalDateTime, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -660636839;

	/**
	 * Setter for <code>public.eventlog.id</code>.
	 */
	public EventlogRecord setId(java.lang.Long value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.eventlog.title</code>.
	 */
	public EventlogRecord setTitle(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.title</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.eventlog.kind</code>.
	 */
	public EventlogRecord setKind(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.kind</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Kind getKind() {
		return (be.wolkmaan.klimtoren.heart.enums.Kind) getValue(2);
	}

	/**
	 * Setter for <code>public.eventlog.message</code>.
	 */
	public EventlogRecord setMessage(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.message</code>.
	 */
	public java.lang.String getMessage() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.eventlog.occured_datetime</code>.
	 */
	public EventlogRecord setOccuredDatetime(java.time.LocalDateTime value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.occured_datetime</code>.
	 */
	public java.time.LocalDateTime getOccuredDatetime() {
		return (java.time.LocalDateTime) getValue(4);
	}

	/**
	 * Setter for <code>public.eventlog.forparty</code>.
	 */
	public EventlogRecord setForparty(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.forparty</code>.
	 */
	public java.lang.Integer getForparty() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.eventlog.forresource</code>.
	 */
	public EventlogRecord setForresource(java.lang.Integer value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.eventlog.forresource</code>.
	 */
	public java.lang.Integer getForresource() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.String, java.time.LocalDateTime, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.String, java.time.LocalDateTime, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Kind> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field5() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.OCCURED_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.FORPARTY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.FORRESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Kind value3() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value5() {
		return getOccuredDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getForparty();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getForresource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value3(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value4(java.lang.String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value5(java.time.LocalDateTime value) {
		setOccuredDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value6(java.lang.Integer value) {
		setForparty(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord value7(java.lang.Integer value) {
		setForresource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventlogRecord values(java.lang.Long value1, java.lang.String value2, be.wolkmaan.klimtoren.heart.enums.Kind value3, java.lang.String value4, java.time.LocalDateTime value5, java.lang.Integer value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventlogRecord
	 */
	public EventlogRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG);
	}

	/**
	 * Create a detached, initialised EventlogRecord
	 */
	public EventlogRecord(java.lang.Long id, java.lang.String title, be.wolkmaan.klimtoren.heart.enums.Kind kind, java.lang.String message, java.time.LocalDateTime occuredDatetime, java.lang.Integer forparty, java.lang.Integer forresource) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG);

		setValue(0, id);
		setValue(1, title);
		setValue(2, kind);
		setValue(3, message);
		setValue(4, occuredDatetime);
		setValue(5, forparty);
		setValue(6, forresource);
	}
}
