/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FullnamesRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> implements org.jooq.Record11<java.lang.Integer, java.lang.Integer, java.sql.Date, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind> {

	private static final long serialVersionUID = -784578245;

	/**
	 * Setter for <code>public.fullnames.id</code>.
	 */
	public FullnamesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.fullnames.forparty</code>.
	 */
	public FullnamesRecord setForparty(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.forparty</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getForparty() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.fullnames.startdate</code>.
	 */
	public FullnamesRecord setStartdate(java.sql.Date value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.startdate</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.sql.Date getStartdate() {
		return (java.sql.Date) getValue(2);
	}

	/**
	 * Setter for <code>public.fullnames.enddate</code>.
	 */
	public FullnamesRecord setEnddate(java.sql.Date value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.enddate</code>.
	 */
	public java.sql.Date getEnddate() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>public.fullnames.givenname</code>.
	 */
	public FullnamesRecord setGivenname(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.givenname</code>.
	 */
	@javax.validation.constraints.Size(max = 40)
	public java.lang.String getGivenname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.fullnames.middlename</code>.
	 */
	public FullnamesRecord setMiddlename(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.middlename</code>.
	 */
	@javax.validation.constraints.Size(max = 40)
	public java.lang.String getMiddlename() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.fullnames.surname</code>.
	 */
	public FullnamesRecord setSurname(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.surname</code>.
	 */
	@javax.validation.constraints.NotNull
	@javax.validation.constraints.Size(max = 40)
	public java.lang.String getSurname() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.fullnames.title</code>.
	 */
	public FullnamesRecord setTitle(java.lang.String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.title</code>.
	 */
	@javax.validation.constraints.Size(max = 50)
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.fullnames.nickname</code>.
	 */
	public FullnamesRecord setNickname(java.lang.String value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.nickname</code>.
	 */
	@javax.validation.constraints.Size(max = 30)
	public java.lang.String getNickname() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>public.fullnames.pronunciation</code>.
	 */
	public FullnamesRecord setPronunciation(java.lang.String value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.pronunciation</code>.
	 */
	@javax.validation.constraints.Size(max = 50)
	public java.lang.String getPronunciation() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>public.fullnames.kind</code>.
	 */
	public FullnamesRecord setKind(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>public.fullnames.kind</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Kind getKind() {
		return (be.wolkmaan.klimtoren.heart.enums.Kind) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.Integer, java.sql.Date, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.Integer, java.sql.Date, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.FORPARTY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.STARTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.ENDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.GIVENNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.MIDDLENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.SURNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.NICKNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.PRONUNCIATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Kind> field11() {
		return be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getForparty();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getStartdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getEnddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGivenname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMiddlename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getSurname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getNickname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getPronunciation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Kind value11() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value2(java.lang.Integer value) {
		setForparty(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value3(java.sql.Date value) {
		setStartdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value4(java.sql.Date value) {
		setEnddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value5(java.lang.String value) {
		setGivenname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value6(java.lang.String value) {
		setMiddlename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value7(java.lang.String value) {
		setSurname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value8(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value9(java.lang.String value) {
		setNickname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value10(java.lang.String value) {
		setPronunciation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord value11(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FullnamesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.sql.Date value3, java.sql.Date value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, be.wolkmaan.klimtoren.heart.enums.Kind value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FullnamesRecord
	 */
	public FullnamesRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES);
	}

	/**
	 * Create a detached, initialised FullnamesRecord
	 */
	public FullnamesRecord(java.lang.Integer id, java.lang.Integer forparty, java.sql.Date startdate, java.sql.Date enddate, java.lang.String givenname, java.lang.String middlename, java.lang.String surname, java.lang.String title, java.lang.String nickname, java.lang.String pronunciation, be.wolkmaan.klimtoren.heart.enums.Kind kind) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES);

		setValue(0, id);
		setValue(1, forparty);
		setValue(2, startdate);
		setValue(3, enddate);
		setValue(4, givenname);
		setValue(5, middlename);
		setValue(6, surname);
		setValue(7, title);
		setValue(8, nickname);
		setValue(9, pronunciation);
		setValue(10, kind);
	}
}
