/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationsRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> implements org.jooq.Record4<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, be.wolkmaan.klimtoren.heart.enums.Kind> {

	private static final long serialVersionUID = 257905781;

	/**
	 * Setter for <code>public.locations.id</code>.
	 */
	public LocationsRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.locations.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.locations.creation_datetime</code>.
	 */
	public LocationsRecord setCreationDatetime(java.time.LocalDateTime value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.locations.creation_datetime</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.time.LocalDateTime getCreationDatetime() {
		return (java.time.LocalDateTime) getValue(1);
	}

	/**
	 * Setter for <code>public.locations.modified_datetime</code>.
	 */
	public LocationsRecord setModifiedDatetime(java.time.LocalDateTime value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.locations.modified_datetime</code>.
	 */
	public java.time.LocalDateTime getModifiedDatetime() {
		return (java.time.LocalDateTime) getValue(2);
	}

	/**
	 * Setter for <code>public.locations.kind</code>.
	 */
	public LocationsRecord setKind(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.locations.kind</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Kind getKind() {
		return (be.wolkmaan.klimtoren.heart.enums.Kind) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, be.wolkmaan.klimtoren.heart.enums.Kind> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, be.wolkmaan.klimtoren.heart.enums.Kind> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS.CREATION_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS.MODIFIED_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Kind> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value2() {
		return getCreationDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value3() {
		return getModifiedDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Kind value4() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationsRecord value2(java.time.LocalDateTime value) {
		setCreationDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationsRecord value3(java.time.LocalDateTime value) {
		setModifiedDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationsRecord value4(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocationsRecord values(java.lang.Integer value1, java.time.LocalDateTime value2, java.time.LocalDateTime value3, be.wolkmaan.klimtoren.heart.enums.Kind value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LocationsRecord
	 */
	public LocationsRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS);
	}

	/**
	 * Create a detached, initialised LocationsRecord
	 */
	public LocationsRecord(java.lang.Integer id, java.time.LocalDateTime creationDatetime, java.time.LocalDateTime modifiedDatetime, be.wolkmaan.klimtoren.heart.enums.Kind kind) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS);

		setValue(0, id);
		setValue(1, creationDatetime);
		setValue(2, modifiedDatetime);
		setValue(3, kind);
	}
}
