/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailboxesRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1222296732;

	/**
	 * Setter for <code>public.mailboxes.id</code>.
	 */
	public MailboxesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.mailboxes.street</code>.
	 */
	public MailboxesRecord setStreet(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.street</code>.
	 */
	@javax.validation.constraints.Size(max = 255)
	public java.lang.String getStreet() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.mailboxes.zip</code>.
	 */
	public MailboxesRecord setZip(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.zip</code>.
	 */
	@javax.validation.constraints.Size(max = 10)
	public java.lang.String getZip() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.mailboxes.city</code>.
	 */
	public MailboxesRecord setCity(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.city</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getCity() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.mailboxes.stateorprovince</code>.
	 */
	public MailboxesRecord setStateorprovince(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.stateorprovince</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getStateorprovince() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.mailboxes.country</code>.
	 */
	public MailboxesRecord setCountry(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.country</code>.
	 */
	public java.lang.Integer getCountry() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.mailboxes.customtype</code>.
	 */
	public MailboxesRecord setCustomtype(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.mailboxes.customtype</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getCustomtype() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.STREET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.ZIP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.STATEORPROVINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.CUSTOMTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStreet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getZip();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getStateorprovince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCustomtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value2(java.lang.String value) {
		setStreet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value3(java.lang.String value) {
		setZip(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value4(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value5(java.lang.String value) {
		setStateorprovince(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value6(java.lang.Integer value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord value7(java.lang.String value) {
		setCustomtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MailboxesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MailboxesRecord
	 */
	public MailboxesRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES);
	}

	/**
	 * Create a detached, initialised MailboxesRecord
	 */
	public MailboxesRecord(java.lang.Integer id, java.lang.String street, java.lang.String zip, java.lang.String city, java.lang.String stateorprovince, java.lang.Integer country, java.lang.String customtype) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES);

		setValue(0, id);
		setValue(1, street);
		setValue(2, zip);
		setValue(3, city);
		setValue(4, stateorprovince);
		setValue(5, country);
		setValue(6, customtype);
	}
}
