/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartiesRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind> {

	private static final long serialVersionUID = -424878363;

	/**
	 * Setter for <code>public.parties.id</code>.
	 */
	public PartiesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.parties.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.parties.display_name</code>.
	 */
	public PartiesRecord setDisplayName(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.parties.display_name</code>.
	 */
	@javax.validation.constraints.Size(max = 255)
	public java.lang.String getDisplayName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.parties.descriptive_information</code>.
	 */
	public PartiesRecord setDescriptiveInformation(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.parties.descriptive_information</code>.
	 */
	public java.lang.String getDescriptiveInformation() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.parties.kind</code>.
	 */
	public PartiesRecord setKind(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.parties.kind</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Kind getKind() {
		return (be.wolkmaan.klimtoren.heart.enums.Kind) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES.DISPLAY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES.DESCRIPTIVE_INFORMATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Kind> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDisplayName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescriptiveInformation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Kind value4() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartiesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartiesRecord value2(java.lang.String value) {
		setDisplayName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartiesRecord value3(java.lang.String value) {
		setDescriptiveInformation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartiesRecord value4(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartiesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, be.wolkmaan.klimtoren.heart.enums.Kind value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PartiesRecord
	 */
	public PartiesRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES);
	}

	/**
	 * Create a detached, initialised PartiesRecord
	 */
	public PartiesRecord(java.lang.Integer id, java.lang.String displayName, java.lang.String descriptiveInformation, be.wolkmaan.klimtoren.heart.enums.Kind kind) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES);

		setValue(0, id);
		setValue(1, displayName);
		setValue(2, descriptiveInformation);
		setValue(3, kind);
	}
}
