/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> implements org.jooq.Record2<java.lang.Integer, be.wolkmaan.klimtoren.heart.enums.Gender> {

	private static final long serialVersionUID = 425244714;

	/**
	 * Setter for <code>public.persons.id</code>.
	 */
	public PersonsRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.persons.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.persons.gender</code>.
	 */
	public PersonsRecord setGender(be.wolkmaan.klimtoren.heart.enums.Gender value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.persons.gender</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Gender getGender() {
		return (be.wolkmaan.klimtoren.heart.enums.Gender) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, be.wolkmaan.klimtoren.heart.enums.Gender> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, be.wolkmaan.klimtoren.heart.enums.Gender> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Gender> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Gender value2() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord value2(be.wolkmaan.klimtoren.heart.enums.Gender value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonsRecord values(java.lang.Integer value1, be.wolkmaan.klimtoren.heart.enums.Gender value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonsRecord
	 */
	public PersonsRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS);
	}

	/**
	 * Create a detached, initialised PersonsRecord
	 */
	public PersonsRecord(java.lang.Integer id, be.wolkmaan.klimtoren.heart.enums.Gender gender) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS);

		setValue(0, id);
		setValue(1, gender);
	}
}
