/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceAttributesRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> implements org.jooq.Record8<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1864010558;

	/**
	 * Setter for <code>public.resource_attributes.id</code>.
	 */
	public ResourceAttributesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.resource_attributes.start_datetime</code>.
	 */
	public ResourceAttributesRecord setStartDatetime(java.time.LocalDateTime value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.start_datetime</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.time.LocalDateTime getStartDatetime() {
		return (java.time.LocalDateTime) getValue(1);
	}

	/**
	 * Setter for <code>public.resource_attributes.end_datetime</code>.
	 */
	public ResourceAttributesRecord setEndDatetime(java.time.LocalDateTime value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.end_datetime</code>.
	 */
	public java.time.LocalDateTime getEndDatetime() {
		return (java.time.LocalDateTime) getValue(2);
	}

	/**
	 * Setter for <code>public.resource_attributes.name</code>.
	 */
	public ResourceAttributesRecord setName(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.name</code>.
	 */
	@javax.validation.constraints.Size(max = 255)
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.resource_attributes.value</code>.
	 */
	public ResourceAttributesRecord setValue(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.value</code>.
	 */
	public java.lang.String getValue() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.resource_attributes.kind</code>.
	 */
	public ResourceAttributesRecord setKind(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.kind</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Kind getKind() {
		return (be.wolkmaan.klimtoren.heart.enums.Kind) getValue(5);
	}

	/**
	 * Setter for <code>public.resource_attributes.forresource</code>.
	 */
	public ResourceAttributesRecord setForresource(java.lang.Integer value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.forresource</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getForresource() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.resource_attributes.forparty</code>.
	 */
	public ResourceAttributesRecord setForparty(java.lang.Integer value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.resource_attributes.forparty</code>.
	 */
	public java.lang.Integer getForparty() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, java.lang.String, java.lang.String, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.START_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.END_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Kind> field6() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.FORRESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.FORPARTY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value2() {
		return getStartDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value3() {
		return getEndDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Kind value6() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getForresource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getForparty();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value2(java.time.LocalDateTime value) {
		setStartDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value3(java.time.LocalDateTime value) {
		setEndDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value5(java.lang.String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value6(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value7(java.lang.Integer value) {
		setForresource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord value8(java.lang.Integer value) {
		setForparty(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceAttributesRecord values(java.lang.Integer value1, java.time.LocalDateTime value2, java.time.LocalDateTime value3, java.lang.String value4, java.lang.String value5, be.wolkmaan.klimtoren.heart.enums.Kind value6, java.lang.Integer value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ResourceAttributesRecord
	 */
	public ResourceAttributesRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES);
	}

	/**
	 * Create a detached, initialised ResourceAttributesRecord
	 */
	public ResourceAttributesRecord(java.lang.Integer id, java.time.LocalDateTime startDatetime, java.time.LocalDateTime endDatetime, java.lang.String name, java.lang.String value, be.wolkmaan.klimtoren.heart.enums.Kind kind, java.lang.Integer forresource, java.lang.Integer forparty) {
		super(be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES);

		setValue(0, id);
		setValue(1, startDatetime);
		setValue(2, endDatetime);
		setValue(3, name);
		setValue(4, value);
		setValue(5, kind);
		setValue(6, forresource);
		setValue(7, forparty);
	}
}
