/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourcesRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> implements org.jooq.Record7<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, java.lang.Integer, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 935144409;

	/**
	 * Setter for <code>public.resources.id</code>.
	 */
	public ResourcesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.resources.start_datetime</code>.
	 */
	public ResourcesRecord setStartDatetime(java.time.LocalDateTime value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.start_datetime</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.time.LocalDateTime getStartDatetime() {
		return (java.time.LocalDateTime) getValue(1);
	}

	/**
	 * Setter for <code>public.resources.end_datetime</code>.
	 */
	public ResourcesRecord setEndDatetime(java.time.LocalDateTime value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.end_datetime</code>.
	 */
	public java.time.LocalDateTime getEndDatetime() {
		return (java.time.LocalDateTime) getValue(2);
	}

	/**
	 * Setter for <code>public.resources.owner</code>.
	 */
	public ResourcesRecord setOwner(java.lang.Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.owner</code>.
	 */
	public java.lang.Integer getOwner() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.resources.kind</code>.
	 */
	public ResourcesRecord setKind(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.kind</code>.
	 */
	public be.wolkmaan.klimtoren.heart.enums.Kind getKind() {
		return (be.wolkmaan.klimtoren.heart.enums.Kind) getValue(4);
	}

	/**
	 * Setter for <code>public.resources.parent</code>.
	 */
	public ResourcesRecord setParent(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.parent</code>.
	 */
	public java.lang.Integer getParent() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.resources.displayName</code>.
	 */
	public ResourcesRecord setDisplayname(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.resources.displayName</code>.
	 */
	@javax.validation.constraints.NotNull
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getDisplayname() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, java.lang.Integer, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.time.LocalDateTime, java.time.LocalDateTime, java.lang.Integer, be.wolkmaan.klimtoren.heart.enums.Kind, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.START_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDateTime> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.END_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.OWNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<be.wolkmaan.klimtoren.heart.enums.Kind> field5() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.KIND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.PARENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.DISPLAYNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value2() {
		return getStartDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDateTime value3() {
		return getEndDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getOwner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.wolkmaan.klimtoren.heart.enums.Kind value5() {
		return getKind();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getParent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDisplayname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value2(java.time.LocalDateTime value) {
		setStartDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value3(java.time.LocalDateTime value) {
		setEndDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value4(java.lang.Integer value) {
		setOwner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value5(be.wolkmaan.klimtoren.heart.enums.Kind value) {
		setKind(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value6(java.lang.Integer value) {
		setParent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord value7(java.lang.String value) {
		setDisplayname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourcesRecord values(java.lang.Integer value1, java.time.LocalDateTime value2, java.time.LocalDateTime value3, java.lang.Integer value4, be.wolkmaan.klimtoren.heart.enums.Kind value5, java.lang.Integer value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ResourcesRecord
	 */
	public ResourcesRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES);
	}

	/**
	 * Create a detached, initialised ResourcesRecord
	 */
	public ResourcesRecord(java.lang.Integer id, java.time.LocalDateTime startDatetime, java.time.LocalDateTime endDatetime, java.lang.Integer owner, be.wolkmaan.klimtoren.heart.enums.Kind kind, java.lang.Integer parent, java.lang.String displayname) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES);

		setValue(0, id);
		setValue(1, startDatetime);
		setValue(2, endDatetime);
		setValue(3, owner);
		setValue(4, kind);
		setValue(5, parent);
		setValue(6, displayname);
	}
}
