/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SiteRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.SiteRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1739823725;

	/**
	 * Setter for <code>public.site.id</code>.
	 */
	public SiteRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.site.id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.site.displayname</code>.
	 */
	public SiteRecord setDisplayname(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.site.displayname</code>.
	 */
	@javax.validation.constraints.Size(max = 50)
	public java.lang.String getDisplayname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.site.descriptiveinformation</code>.
	 */
	public SiteRecord setDescriptiveinformation(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.site.descriptiveinformation</code>.
	 */
	public java.lang.String getDescriptiveinformation() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.site.customtype</code>.
	 */
	public SiteRecord setCustomtype(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.site.customtype</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getCustomtype() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Site.SITE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Site.SITE.DISPLAYNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Site.SITE.DESCRIPTIVEINFORMATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return be.wolkmaan.klimtoren.heart.model.tables.Site.SITE.CUSTOMTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDisplayname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescriptiveinformation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCustomtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiteRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiteRecord value2(java.lang.String value) {
		setDisplayname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiteRecord value3(java.lang.String value) {
		setDescriptiveinformation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiteRecord value4(java.lang.String value) {
		setCustomtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiteRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SiteRecord
	 */
	public SiteRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Site.SITE);
	}

	/**
	 * Create a detached, initialised SiteRecord
	 */
	public SiteRecord(java.lang.Integer id, java.lang.String displayname, java.lang.String descriptiveinformation, java.lang.String customtype) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Site.SITE);

		setValue(0, id);
		setValue(1, displayname);
		setValue(2, descriptiveinformation);
		setValue(3, customtype);
	}
}
