/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TelephonesRecord extends org.jooq.impl.UpdatableRecordImpl<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -15806306;

	/**
	 * Setter for <code>public.telephones.location_id</code>.
	 */
	public TelephonesRecord setLocationId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.telephones.location_id</code>.
	 */
	@javax.validation.constraints.NotNull
	public java.lang.Integer getLocationId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.telephones.number</code>.
	 */
	public TelephonesRecord setNumber(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.telephones.number</code>.
	 */
	@javax.validation.constraints.Size(max = 20)
	public java.lang.String getNumber() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.telephones.customtype</code>.
	 */
	public TelephonesRecord setCustomtype(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.telephones.customtype</code>.
	 */
	@javax.validation.constraints.Size(max = 100)
	public java.lang.String getCustomtype() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES.LOCATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES.CUSTOMTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getLocationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCustomtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TelephonesRecord value1(java.lang.Integer value) {
		setLocationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TelephonesRecord value2(java.lang.String value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TelephonesRecord value3(java.lang.String value) {
		setCustomtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TelephonesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TelephonesRecord
	 */
	public TelephonesRecord() {
		super(be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES);
	}

	/**
	 * Create a detached, initialised TelephonesRecord
	 */
	public TelephonesRecord(java.lang.Integer locationId, java.lang.String number, java.lang.String customtype) {
		super(be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES);

		setValue(0, locationId);
		setValue(1, number);
		setValue(2, customtype);
	}
}
