/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord, java.lang.Integer> IDENTITY_COUNTRIES = Identities0.IDENTITY_COUNTRIES;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord, java.lang.Long> IDENTITY_EVENTLOG = Identities0.IDENTITY_EVENTLOG;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.Integer> IDENTITY_FULLNAMES = Identities0.IDENTITY_FULLNAMES;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, java.lang.Integer> IDENTITY_LOCATIONS = Identities0.IDENTITY_LOCATIONS;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.lang.Integer> IDENTITY_P2P_RELATIONS = Identities0.IDENTITY_P2P_RELATIONS;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, java.lang.Integer> IDENTITY_PARTIES = Identities0.IDENTITY_PARTIES;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.Integer> IDENTITY_PARTY_ATTRIBUTES = Identities0.IDENTITY_PARTY_ATTRIBUTES;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord, java.lang.Integer> IDENTITY_PARTY_RESOURCES = Identities0.IDENTITY_PARTY_RESOURCES;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.Integer> IDENTITY_RESOURCE_ATTRIBUTES = Identities0.IDENTITY_RESOURCE_ATTRIBUTES;
	public static final org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.Integer> IDENTITY_RESOURCES = Identities0.IDENTITY_RESOURCES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> AUTHENTICATION_PKEY = UniqueKeys0.AUTHENTICATION_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> AUTHENTICATION_USERNAME_KEY = UniqueKeys0.AUTHENTICATION_USERNAME_KEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> COUNTRIES_PKEY = UniqueKeys0.COUNTRIES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> COUNTRIES_CODE_KEY = UniqueKeys0.COUNTRIES_CODE_KEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> EMAILS_PKEY = UniqueKeys0.EMAILS_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord> EVENTLOG_PKEY = UniqueKeys0.EVENTLOG_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> FULLNAMES_PKEY = UniqueKeys0.FULLNAMES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.IpsRecord> IPS_PKEY = UniqueKeys0.IPS_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> LOCATIONS_PKEY = UniqueKeys0.LOCATIONS_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> MAILBOXES_PKEY = UniqueKeys0.MAILBOXES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> ORGANIZATIONS_PKEY = UniqueKeys0.ORGANIZATIONS_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> P2P_RELATIONS_PKEY = UniqueKeys0.P2P_RELATIONS_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PARTIES_PKEY = UniqueKeys0.PARTIES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> PARTY_ATTRIBUTES_PKEY = UniqueKeys0.PARTY_ATTRIBUTES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord> PARTY_RESOURCES_PKEY = UniqueKeys0.PARTY_RESOURCES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> PERSONS_PKEY = UniqueKeys0.PERSONS_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> RESOURCE_ATTRIBUTES_PKEY = UniqueKeys0.RESOURCE_ATTRIBUTES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> RESOURCES_PKEY = UniqueKeys0.RESOURCES_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.SiteRecord> SITE_PKEY = UniqueKeys0.SITE_PKEY;
	public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> TELEPHONES_PKEY = UniqueKeys0.TELEPHONES_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> AUTHENTICATION__AUTHENTICATION_ID_FKEY = ForeignKeys0.AUTHENTICATION__AUTHENTICATION_ID_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> EMAILS__EMAILS_ID_FKEY = ForeignKeys0.EMAILS__EMAILS_ID_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> EVENTLOG__EVENTLOG_FORPARTY_FKEY = ForeignKeys0.EVENTLOG__EVENTLOG_FORPARTY_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> EVENTLOG__EVENTLOG_FORRESOURCE_FKEY = ForeignKeys0.EVENTLOG__EVENTLOG_FORRESOURCE_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> FULLNAMES__FULLNAMES_FORPARTY_FKEY = ForeignKeys0.FULLNAMES__FULLNAMES_FORPARTY_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.IpsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> IPS__IPS_ID_FKEY = ForeignKeys0.IPS__IPS_ID_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> MAILBOXES__MAILBOXES_ID_FKEY = ForeignKeys0.MAILBOXES__MAILBOXES_ID_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> MAILBOXES__MAILBOXES_COUNTRY_FKEY = ForeignKeys0.MAILBOXES__MAILBOXES_COUNTRY_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> ORGANIZATIONS__ORGANIZATIONS_ID_FKEY = ForeignKeys0.ORGANIZATIONS__ORGANIZATIONS_ID_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> P2P_RELATIONS__P2P_RELATIONS_CONTEXT_FKEY = ForeignKeys0.P2P_RELATIONS__P2P_RELATIONS_CONTEXT_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> P2P_RELATIONS__P2P_RELATIONS_REFERENCE_FKEY = ForeignKeys0.P2P_RELATIONS__P2P_RELATIONS_REFERENCE_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PARTY_ATTRIBUTES__PARTY_ATTRIBUTES_FORPARTY_FKEY = ForeignKeys0.PARTY_ATTRIBUTES__PARTY_ATTRIBUTES_FORPARTY_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PARTY_RESOURCES__PARTY_RESOURCES_FORPARTY_FKEY = ForeignKeys0.PARTY_RESOURCES__PARTY_RESOURCES_FORPARTY_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> PARTY_RESOURCES__PARTY_RESOURCES_USERESOURCE_FKEY = ForeignKeys0.PARTY_RESOURCES__PARTY_RESOURCES_USERESOURCE_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PERSONS__PERSONS_ID_FKEY = ForeignKeys0.PERSONS__PERSONS_ID_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORRESOURCE_FKEY = ForeignKeys0.RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORRESOURCE_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORPARTY_FKEY = ForeignKeys0.RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORPARTY_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> RESOURCES__RESOURCES_OWNER_FKEY = ForeignKeys0.RESOURCES__RESOURCES_OWNER_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> RESOURCES__RESOURCES_PARENT_FKEY = ForeignKeys0.RESOURCES__RESOURCES_PARENT_FKEY;
	public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.SiteRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> SITE__SITE_ID_FKEY = ForeignKeys0.SITE__SITE_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord, java.lang.Integer> IDENTITY_COUNTRIES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES, be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord, java.lang.Long> IDENTITY_EVENTLOG = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG, be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, java.lang.Integer> IDENTITY_FULLNAMES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES, be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord, java.lang.Integer> IDENTITY_LOCATIONS = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS, be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, java.lang.Integer> IDENTITY_P2P_RELATIONS = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord, java.lang.Integer> IDENTITY_PARTIES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES, be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, java.lang.Integer> IDENTITY_PARTY_ATTRIBUTES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord, java.lang.Integer> IDENTITY_PARTY_RESOURCES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, java.lang.Integer> IDENTITY_RESOURCE_ATTRIBUTES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.ID);
		public static org.jooq.Identity<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, java.lang.Integer> IDENTITY_RESOURCES = createIdentity(be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> AUTHENTICATION_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION, be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord> AUTHENTICATION_USERNAME_KEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION, be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION.USERNAME);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> COUNTRIES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES, be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> COUNTRIES_CODE_KEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES, be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES.CODE);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord> EMAILS_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS, be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord> EVENTLOG_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG, be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord> FULLNAMES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES, be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.IpsRecord> IPS_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Ips.IPS, be.wolkmaan.klimtoren.heart.model.tables.Ips.IPS.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> LOCATIONS_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS, be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord> MAILBOXES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES, be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord> ORGANIZATIONS_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Organizations.ORGANIZATIONS, be.wolkmaan.klimtoren.heart.model.tables.Organizations.ORGANIZATIONS.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord> P2P_RELATIONS_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PARTIES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES, be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord> PARTY_ATTRIBUTES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord> PARTY_RESOURCES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord> PERSONS_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS, be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord> RESOURCE_ATTRIBUTES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> RESOURCES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.SiteRecord> SITE_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Site.SITE, be.wolkmaan.klimtoren.heart.model.tables.Site.SITE.ID);
		public static final org.jooq.UniqueKey<be.wolkmaan.klimtoren.heart.model.tables.records.TelephonesRecord> TELEPHONES_PKEY = createUniqueKey(be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES, be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES.LOCATION_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.AuthenticationRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> AUTHENTICATION__AUTHENTICATION_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION, be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION.ID);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EmailsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> EMAILS__EMAILS_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.LOCATIONS_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS, be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS.ID);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> EVENTLOG__EVENTLOG_FORPARTY_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG, be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.FORPARTY);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.EventlogRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> EVENTLOG__EVENTLOG_FORRESOURCE_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG, be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG.FORRESOURCE);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.FullnamesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> FULLNAMES__FULLNAMES_FORPARTY_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES, be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES.FORPARTY);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.IpsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> IPS__IPS_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.LOCATIONS_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Ips.IPS, be.wolkmaan.klimtoren.heart.model.tables.Ips.IPS.ID);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> MAILBOXES__MAILBOXES_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.LOCATIONS_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES, be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.ID);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.MailboxesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.CountriesRecord> MAILBOXES__MAILBOXES_COUNTRY_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.COUNTRIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES, be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES.COUNTRY);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.OrganizationsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> ORGANIZATIONS__ORGANIZATIONS_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Organizations.ORGANIZATIONS, be.wolkmaan.klimtoren.heart.model.tables.Organizations.ORGANIZATIONS.ID);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> P2P_RELATIONS__P2P_RELATIONS_CONTEXT_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS.CONTEXT);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.P2pRelationsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> P2P_RELATIONS__P2P_RELATIONS_REFERENCE_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS, be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS.REFERENCE);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyAttributesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PARTY_ATTRIBUTES__PARTY_ATTRIBUTES_FORPARTY_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES.FORPARTY);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PARTY_RESOURCES__PARTY_RESOURCES_FORPARTY_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES.FORPARTY);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PartyResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> PARTY_RESOURCES__PARTY_RESOURCES_USERESOURCE_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES.USERESOURCE);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.PersonsRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> PERSONS__PERSONS_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS, be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS.ID);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORRESOURCE_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.FORRESOURCE);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourceAttributesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> RESOURCE_ATTRIBUTES__RESOURCE_ATTRIBUTES_FORPARTY_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES, be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES.FORPARTY);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.PartiesRecord> RESOURCES__RESOURCES_OWNER_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.PARTIES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.OWNER);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord, be.wolkmaan.klimtoren.heart.model.tables.records.ResourcesRecord> RESOURCES__RESOURCES_PARENT_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.RESOURCES_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES, be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES.PARENT);
		public static final org.jooq.ForeignKey<be.wolkmaan.klimtoren.heart.model.tables.records.SiteRecord, be.wolkmaan.klimtoren.heart.model.tables.records.LocationsRecord> SITE__SITE_ID_FKEY = createForeignKey(be.wolkmaan.klimtoren.heart.model.Keys.LOCATIONS_PKEY, be.wolkmaan.klimtoren.heart.model.tables.Site.SITE, be.wolkmaan.klimtoren.heart.model.tables.Site.SITE.ID);
	}
}
