/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.countries_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> COUNTRIES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("countries_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.eventlog_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> EVENTLOG_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("eventlog_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.fullnames_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> FULLNAMES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("fullnames_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.locations_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> LOCATIONS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("locations_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.p2p_relations_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> P2P_RELATIONS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("p2p_relations_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.parties_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> PARTIES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("parties_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.party_attributes_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> PARTY_ATTRIBUTES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("party_attributes_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.party_resources_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> PARTY_RESOURCES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("party_resources_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.resource_attributes_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> RESOURCE_ATTRIBUTES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("resource_attributes_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.resources_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> RESOURCES_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("resources_id_seq", be.wolkmaan.klimtoren.heart.model.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
