/**
 * This class is generated by jOOQ
 */
package be.wolkmaan.klimtoren.heart.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.authentication
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Authentication AUTHENTICATION = be.wolkmaan.klimtoren.heart.model.tables.Authentication.AUTHENTICATION;

	/**
	 * The table public.countries
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Countries COUNTRIES = be.wolkmaan.klimtoren.heart.model.tables.Countries.COUNTRIES;

	/**
	 * The table public.emails
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Emails EMAILS = be.wolkmaan.klimtoren.heart.model.tables.Emails.EMAILS;

	/**
	 * The table public.eventlog
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Eventlog EVENTLOG = be.wolkmaan.klimtoren.heart.model.tables.Eventlog.EVENTLOG;

	/**
	 * The table public.fullnames
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Fullnames FULLNAMES = be.wolkmaan.klimtoren.heart.model.tables.Fullnames.FULLNAMES;

	/**
	 * The table public.ips
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Ips IPS = be.wolkmaan.klimtoren.heart.model.tables.Ips.IPS;

	/**
	 * The table public.locations
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Locations LOCATIONS = be.wolkmaan.klimtoren.heart.model.tables.Locations.LOCATIONS;

	/**
	 * The table public.mailboxes
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Mailboxes MAILBOXES = be.wolkmaan.klimtoren.heart.model.tables.Mailboxes.MAILBOXES;

	/**
	 * The table public.organizations
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Organizations ORGANIZATIONS = be.wolkmaan.klimtoren.heart.model.tables.Organizations.ORGANIZATIONS;

	/**
	 * The table public.p2p_relations
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.P2pRelations P2P_RELATIONS = be.wolkmaan.klimtoren.heart.model.tables.P2pRelations.P2P_RELATIONS;

	/**
	 * The table public.parties
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Parties PARTIES = be.wolkmaan.klimtoren.heart.model.tables.Parties.PARTIES;

	/**
	 * The table public.party_attributes
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes PARTY_ATTRIBUTES = be.wolkmaan.klimtoren.heart.model.tables.PartyAttributes.PARTY_ATTRIBUTES;

	/**
	 * The table public.party_resources
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.PartyResources PARTY_RESOURCES = be.wolkmaan.klimtoren.heart.model.tables.PartyResources.PARTY_RESOURCES;

	/**
	 * The table public.persons
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Persons PERSONS = be.wolkmaan.klimtoren.heart.model.tables.Persons.PERSONS;

	/**
	 * The table public.resource_attributes
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes RESOURCE_ATTRIBUTES = be.wolkmaan.klimtoren.heart.model.tables.ResourceAttributes.RESOURCE_ATTRIBUTES;

	/**
	 * The table public.resources
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Resources RESOURCES = be.wolkmaan.klimtoren.heart.model.tables.Resources.RESOURCES;

	/**
	 * The table public.site
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Site SITE = be.wolkmaan.klimtoren.heart.model.tables.Site.SITE;

	/**
	 * The table public.telephones
	 */
	public static final be.wolkmaan.klimtoren.heart.model.tables.Telephones TELEPHONES = be.wolkmaan.klimtoren.heart.model.tables.Telephones.TELEPHONES;
}
